
#include "SysTick.h"

/*
 STK_AHB_DIVIDED_BY_8
 STK_AHB_CLOCK
 */
#define 	STK_CLKSOURCE_MODE		STK_AHB_DIVIDED_BY_8

/*
STK_EXCEPTION_DISABLE
STK_EXCEPTION_ENABLE
 */
#define STK_EXCEPTION_REQUEST	STK_EXCEPTION_ENABLE
